insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Leon Themann', 'Westridge', '1995-09-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Noelyn Foyle', 'Harper', '2004-11-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Pearl Willford', 'Norway Maple', '2013-06-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Regina Balcombe', 'Buena Vista', '2009-10-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rana Bernardini', 'Sundown', '2005-11-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dun Valente', 'Lighthouse Bay', '2003-12-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sandor Alday', 'Redwing', '2015-03-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('My Bentje', 'Fair Oaks', '2005-04-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Felicle Blanc', 'Towne', '1994-01-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Teresita Youd', 'Mallory', '2012-11-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dora Haccleton', 'Hazelcrest', '2008-04-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Suellen Cleverley', 'Thierer', '2018-09-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Joella Rylands', '5th', '2018-11-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Luca Klimpt', 'Fairview', '2005-11-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dore Pocknoll', 'Golf', '2003-12-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gil McKeachie', 'Moose', '1997-09-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Billy McArtan', 'Del Mar', '1997-11-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jody Patching', 'Basil', '2009-03-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hedwig McKinnell', 'Packers', '2005-03-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Correy Maclaine', 'Sutteridge', '2019-12-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ennis Baus', 'Waubesa', '2018-08-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lidia Lampett', 'Straubel', '2016-03-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Axel Crippen', 'Ridgeview', '2009-12-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Otes Edwards', 'Nelson', '1995-05-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Myrah Kindle', 'Texas', '1990-08-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Guthrey Damiral', 'Arkansas', '1996-03-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mic D''Emanuele', 'Victoria', '1995-04-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dev Sirkett', 'Merchant', '2015-10-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Boone Byers', 'La Follette', '1992-07-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Esdras Hendrich', 'Eagle Crest', '1996-01-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nedi Snibson', 'Fulton', '2006-12-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Manuel Bagby', 'Ohio', '1996-04-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mike Chalcraft', 'Hansons', '2001-01-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Adria Southern', 'Hansons', '2001-04-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Esdras Villaron', 'Straubel', '1991-04-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ajay Waltering', 'Corscot', '2009-03-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bentlee Marquand', 'Crownhardt', '2019-08-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Francis Edghinn', 'Sutteridge', '1996-05-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cort Whichelow', 'Basil', '2017-12-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tonnie Carefull', 'Grayhawk', '2010-08-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Wilmar Claisse', 'Calypso', '2018-06-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Linc Jiri', 'Surrey', '1998-12-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Isabella MacCarrick', 'Parkside', '2018-04-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Town Durdy', 'Golf Course', '2014-02-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Harriot Rae', 'Valley Edge', '1997-12-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Julia Broadhead', 'Northfield', '2018-04-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cathlene Simes', 'Spenser', '2016-10-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Raymond Blenkhorn', 'La Follette', '1992-11-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Garner Connealy', 'Doe Crossing', '2000-06-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Christie Grise', 'Hintze', '2015-02-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Traci Gullick', 'Mcbride', '1998-09-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Corbie Doghartie', 'Kenwood', '2013-08-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hannie Vost', 'Parkside', '2006-05-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Locke Sidaway', 'Kensington', '1996-09-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Brendin Lindroos', 'Crest Line', '1994-05-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maryann Beuscher', '5th', '2018-01-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sioux Linney', 'Monterey', '2019-04-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Axe Samarth', 'Village', '2017-08-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Eugine Eynaud', 'Derek', '2003-08-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Flemming Duplain', 'Riverside', '2015-10-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Deva Alessandretti', 'Hanson', '2000-07-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tawsha Bonney', 'Bowman', '2004-10-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marlyn Dudney', 'Dryden', '2005-03-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Auberta Aireton', 'Nelson', '2016-10-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sara Fuxman', 'Valley Edge', '2010-08-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lars Winspeare', 'Daystar', '2001-10-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Coriss Richold', 'Dakota', '2015-03-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mahalia Hannaby', 'Goodland', '1991-12-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ginnie Causey', 'Main', '2017-07-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Teodor Writer', 'Bultman', '2005-07-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Osmond Inston', 'Dwight', '2018-05-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Joan Jeandeau', 'Weeping Birch', '2018-06-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Blair Balsdon', 'Lien', '1994-12-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Korey Howick', 'Carpenter', '1993-12-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Barr Brennon', 'Sutherland', '2016-02-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Reggis Carle', 'Continental', '2016-06-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jacques Rosle', 'Rigney', '1997-05-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Demeter Kochl', 'Bonner', '2003-07-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Any Cranmer', 'Independence', '2006-01-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Arleta Lytlle', 'Service', '2020-02-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Chloris Peealess', 'Hudson', '2019-09-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ottilie Midgley', 'Sommers', '1992-05-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Xena Scoyne', 'Bluejay', '1997-01-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sidney Westcott', 'Waywood', '2000-12-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Harrietta Hassekl', 'Thompson', '2008-09-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Grantham MacNockater', 'Saint Paul', '2016-09-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Friederike Gehrts', 'Victoria', '2002-08-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fritz Roff', 'Surrey', '1990-12-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Donielle Hort', 'Farwell', '2013-02-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jannel Brumen', 'Ridgeview', '1992-08-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gilli Ilewicz', 'Hansons', '1995-04-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Suzanna Gooday', 'South', '2006-12-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Quinton Padden', '1st', '1998-03-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bernadina Skayman', 'Crest Line', '2008-02-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cynthea Newhouse', 'Artisan', '2019-04-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nate Gascoyne', 'Bashford', '2007-01-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Muffin Cottam', 'Lighthouse Bay', '1992-08-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jaime Humpherston', 'Annamark', '1997-12-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dylan Parffrey', 'Oriole', '2005-03-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gayle Flement', 'Hermina', '1992-09-25');
