insert into tren (modelo, capacidad) values ('Mighty Max Macro', 1);
insert into tren (modelo, capacidad) values ('RDX', 2);
insert into tren (modelo, capacidad) values ('Armada', 3);
insert into tren (modelo, capacidad) values ('Boxster', 4);
insert into tren (modelo, capacidad) values ('VehiCROSS', 5);
insert into tren (modelo, capacidad) values ('9-5', 6);
insert into tren (modelo, capacidad) values ('SLX', 7);
insert into tren (modelo, capacidad) values ('Club Wagon', 8);
insert into tren (modelo, capacidad) values ('LeSabre', 9);
insert into tren (modelo, capacidad) values ('S6', 10);
insert into tren (modelo, capacidad) values ('TL', 11);
insert into tren (modelo, capacidad) values ('Century', 12);
insert into tren (modelo, capacidad) values ('F-Series', 13);
insert into tren (modelo, capacidad) values ('Skylark', 14);
insert into tren (modelo, capacidad) values ('6000', 15);
insert into tren (modelo, capacidad) values ('XC70', 16);
insert into tren (modelo, capacidad) values ('Versa', 17);
insert into tren (modelo, capacidad) values ('Stealth', 18);
insert into tren (modelo, capacidad) values ('Esprit', 19);
insert into tren (modelo, capacidad) values ('Festiva', 20);
insert into tren (modelo, capacidad) values ('Town Car', 21);
insert into tren (modelo, capacidad) values ('Jetta', 22);
insert into tren (modelo, capacidad) values ('Pacifica', 23);
insert into tren (modelo, capacidad) values ('MPV', 24);
insert into tren (modelo, capacidad) values ('R8', 25);
insert into tren (modelo, capacidad) values ('S4', 26);
insert into tren (modelo, capacidad) values ('MX-5', 27);
insert into tren (modelo, capacidad) values ('FX', 28);
insert into tren (modelo, capacidad) values ('Elise', 29);
insert into tren (modelo, capacidad) values ('MR2', 30);
insert into tren (modelo, capacidad) values ('F150', 31);
insert into tren (modelo, capacidad) values ('2500', 32);
insert into tren (modelo, capacidad) values ('Ram 1500', 33);
insert into tren (modelo, capacidad) values ('Escort', 34);
insert into tren (modelo, capacidad) values ('H1', 35);
insert into tren (modelo, capacidad) values ('Rabbit', 36);
insert into tren (modelo, capacidad) values ('Passport', 37);
insert into tren (modelo, capacidad) values ('Odyssey', 38);
insert into tren (modelo, capacidad) values ('A8', 39);
insert into tren (modelo, capacidad) values ('Ram Van 2500', 40);
insert into tren (modelo, capacidad) values ('Range Rover', 41);
insert into tren (modelo, capacidad) values ('Express 1500', 42);
insert into tren (modelo, capacidad) values ('J', 43);
insert into tren (modelo, capacidad) values ('Range Rover', 44);
insert into tren (modelo, capacidad) values ('GTO', 45);
insert into tren (modelo, capacidad) values ('E-Class', 46);
insert into tren (modelo, capacidad) values ('Bonneville', 47);
insert into tren (modelo, capacidad) values ('Grand Cherokee', 48);
insert into tren (modelo, capacidad) values ('Ram Van 1500', 49);
insert into tren (modelo, capacidad) values ('Dakota', 50);
insert into tren (modelo, capacidad) values ('Sorento', 51);
insert into tren (modelo, capacidad) values ('Ascender', 52);
insert into tren (modelo, capacidad) values ('G-Class', 53);
insert into tren (modelo, capacidad) values ('LeSabre', 54);
insert into tren (modelo, capacidad) values ('New Beetle', 55);
insert into tren (modelo, capacidad) values ('XL-7', 56);
insert into tren (modelo, capacidad) values ('Taurus', 57);
insert into tren (modelo, capacidad) values ('Equinox', 58);
insert into tren (modelo, capacidad) values ('A7', 59);
insert into tren (modelo, capacidad) values ('Cabriolet', 60);
insert into tren (modelo, capacidad) values ('Jetta', 61);
insert into tren (modelo, capacidad) values ('Durango', 62);
insert into tren (modelo, capacidad) values ('Ram Van 3500', 63);
insert into tren (modelo, capacidad) values ('Sunfire', 64);
insert into tren (modelo, capacidad) values ('MX-6', 65);
insert into tren (modelo, capacidad) values ('F250', 66);
insert into tren (modelo, capacidad) values ('E-Series', 67);
insert into tren (modelo, capacidad) values ('Exige', 68);
insert into tren (modelo, capacidad) values ('QX56', 69);
insert into tren (modelo, capacidad) values ('G', 70);
insert into tren (modelo, capacidad) values ('Accord', 71);
insert into tren (modelo, capacidad) values ('2500', 72);
insert into tren (modelo, capacidad) values ('Grand Cherokee', 73);
insert into tren (modelo, capacidad) values ('H2', 74);
insert into tren (modelo, capacidad) values ('Thunderbird', 75);
insert into tren (modelo, capacidad) values ('DeVille', 76);
insert into tren (modelo, capacidad) values ('Viper', 77);
insert into tren (modelo, capacidad) values ('MX-5', 78);
insert into tren (modelo, capacidad) values ('Sephia', 79);
insert into tren (modelo, capacidad) values ('G6', 80);
insert into tren (modelo, capacidad) values ('Ram Van 2500', 81);
insert into tren (modelo, capacidad) values ('Legacy', 82);
insert into tren (modelo, capacidad) values ('Silhouette', 83);
insert into tren (modelo, capacidad) values ('Challenger', 84);
insert into tren (modelo, capacidad) values ('XL-7', 85);
insert into tren (modelo, capacidad) values ('STS-V', 86);
insert into tren (modelo, capacidad) values ('Xtra', 87);
insert into tren (modelo, capacidad) values ('Horizon', 88);
insert into tren (modelo, capacidad) values ('F250', 89);
insert into tren (modelo, capacidad) values ('M5', 90);
insert into tren (modelo, capacidad) values ('Grand Voyager', 91);
insert into tren (modelo, capacidad) values ('Q7', 92);
insert into tren (modelo, capacidad) values ('Swift', 93);
insert into tren (modelo, capacidad) values ('Suburban 2500', 94);
insert into tren (modelo, capacidad) values ('Diamante', 95);
insert into tren (modelo, capacidad) values ('rio', 96);
insert into tren (modelo, capacidad) values ('SLX', 97);
insert into tren (modelo, capacidad) values ('Suburban 2500', 98);
insert into tren (modelo, capacidad) values ('GTO', 99);
insert into tren (modelo, capacidad) values ('Rendezvous', 100);
